namespace: dev
resources:
  - namespace.yaml
  - http-route.yaml
  - ../../base
  - secrets/postgres-secret.yaml
  - secrets/auth-secret.yaml
  - configmaps/frontend-cm.yaml
  - configmaps/auth-cm.yaml
images:
  - name: ghcr.io/corentin-dupaigne/fullstack_project/auth
    newTag: dev
  - name: ghcr.io/corentin-dupaigne/fullstack_project/frontend
    newTag: dev
