apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-cm
data:
  AUTH_URL: "https://dev.condensation.corentindupaigne.com"
  API_URL: "http://auth-svc"
  REDIRECT_URI: "https://dev.condensation.corentindupaigne.com/api/auth/callback"
  HOSTNAME: "0.0.0.0"
  CLIENT_ID:

