import {
  type HeroSlide,
  type Game,
  type BestsellerGame,
  type DealTier,
  type Platform,
} from "./types";

export const heroSlides: HeroSlide[] = [
  {
    id: "1",
    title: "CyberStellar 2088",
    subtitle:
      "Experience the neon-drenched future of tactical combat in the most anticipated RPG of the decade.",
    ctaText: "Pre-order Now",
    ctaLink: "#",
    price: 59.99,
    gradientFrom: "#0f2027",
    gradientTo: "#203a43",
  },
  {
    id: "2",
    title: "Mythic Origins: Reborn",
    subtitle:
      "Descend into a hand-crafted mythological world where every choice reshapes destiny.",
    ctaText: "Buy Now",
    ctaLink: "#",
    price: 49.99,
    gradientFrom: "#1a0033",
    gradientTo: "#330066",
  },
  {
    id: "3",
    title: "Velocity X-Treme Pro",
    subtitle:
      "Push the limits of speed in the most photorealistic racing experience ever made.",
    ctaText: "Shop Now",
    ctaLink: "#",
    price: 39.99,
    gradientFrom: "#1c1c00",
    gradientTo: "#3a3a00",
  },
];

export const recommendedGames: Game[] = [
  {
    id: "r1",
    title: "Elden Shadow Realm",
    slug: "elden-shadow-realm",
    platform: "steam",
    genres: ["Action", "Open World"],
    price: 33.99,
    originalPrice: 39.99,
    discountPercent: 15,
    badges: ["discount"],
  },
  {
    id: "r2",
    title: "Starfield Explorer",
    slug: "starfield-explorer",
    platform: "steam",
    genres: ["Sci-Fi", "RPG"],
    price: 41.99,
    originalPrice: 69.99,
    discountPercent: 40,
    badges: ["discount"],
  },
  {
    id: "r3",
    title: "Velocity X-Treme",
    slug: "velocity-x-treme",
    platform: "steam",
    genres: ["Racing", "Sports"],
    price: 29.99,
    badges: ["rare"],
  },
  {
    id: "r4",
    title: "Kingdom Come II",
    slug: "kingdom-come-ii",
    platform: "steam",
    genres: ["Historical", "RPG"],
    price: 49.99,
    badges: [],
  },
  {
    id: "r5",
    title: "Phantom Blade",
    slug: "phantom-blade",
    platform: "epic",
    genres: ["Action", "Stealth"],
    price: 24.99,
    originalPrice: 34.99,
    discountPercent: 29,
    badges: ["discount"],
  },
  {
    id: "r6",
    title: "Nova Frontier",
    slug: "nova-frontier",
    platform: "steam",
    genres: ["Strategy", "Sci-Fi"],
    price: 19.99,
    badges: ["new"],
  },
];

export const bestsellerGames: BestsellerGame[] = [
  {
    id: "b1",
    title: "Strike Team Delta",
    slug: "strike-team-delta",
    platform: "steam",
    genres: ["FPS", "Tactical"],
    price: 14.5,
    originalPrice: 19.99,
    discountPercent: 25,
    badges: ["discount"],
    rank: 1,
  },
  {
    id: "b2",
    title: "Neon Pulse",
    slug: "neon-pulse",
    platform: "steam",
    genres: ["Cyberpunk", "Action"],
    price: 19.99,
    badges: ["popular"],
    rank: 2,
  },
  {
    id: "b3",
    title: "Mythic Origins",
    slug: "mythic-origins",
    platform: "steam",
    genres: ["RPG", "Fantasy"],
    price: 9.99,
    originalPrice: 19.99,
    discountPercent: 50,
    badges: ["discount"],
    rank: 3,
  },
];

export const newReleases: Game[] = [
  {
    id: "n1",
    title: "Ghost Protocol: Zero",
    slug: "ghost-protocol-zero",
    platform: "steam",
    genres: ["Stealth", "Action"],
    price: 59.99,
    badges: ["new"],
    releasedAgo: "Released 2 days ago",
  },
  {
    id: "n2",
    title: "Arcade Legends",
    slug: "arcade-legends",
    platform: "steam",
    genres: ["Arcade", "Retro"],
    price: 12.49,
    badges: ["new"],
    releasedAgo: "Released Yesterday",
  },
  {
    id: "n3",
    title: "Final Hour: Remastered",
    slug: "final-hour-remastered",
    platform: "steam",
    genres: ["FPS", "Remaster"],
    price: 39.99,
    badges: ["new"],
    releasedAgo: "Released Today",
  },
];

export const preOrders: Game[] = [
  {
    id: "p1",
    title: "Beyond The Void",
    slug: "beyond-the-void",
    platform: "steam",
    genres: ["Sci-Fi", "Adventure"],
    price: 69.99,
    badges: ["pre-order"],
    timeLeft: "12 Days Left",
  },
  {
    id: "p2",
    title: "Kingdoms of Dust",
    slug: "kingdoms-of-dust",
    platform: "steam",
    genres: ["Strategy", "Medieval"],
    price: 44.99,
    badges: ["pre-order"],
    timeLeft: "3 Weeks Left",
  },
  {
    id: "p3",
    title: "Silent Strike",
    slug: "silent-strike",
    platform: "steam",
    genres: ["Stealth", "Thriller"],
    price: 59.99,
    badges: ["pre-order"],
    timeLeft: "Coming Q4",
  },
];

export const dealTiers: DealTier[] = [
  {
    label: "Under €5",
    maxPrice: 5,
    games: [
      {
        id: "d1",
        title: "Shadow Runner",
        slug: "shadow-runner",
        platform: "steam",
        genres: ["Platformer"],
        price: 1.99,
        originalPrice: 14.99,
        discountPercent: 87,
        badges: ["discount"],
      },
      {
        id: "d2",
        title: "Pixel Rogue",
        slug: "pixel-rogue",
        platform: "steam",
        genres: ["Roguelike"],
        price: 0.89,
        originalPrice: 9.99,
        discountPercent: 91,
        badges: ["discount"],
      },
      {
        id: "d3",
        title: "Lofi Odyssey",
        slug: "lofi-odyssey",
        platform: "steam",
        genres: ["Adventure"],
        price: 4.5,
        originalPrice: 19.0,
        discountPercent: 76,
        badges: ["discount"],
      },
      {
        id: "d4",
        title: "Deep Sea Survival",
        slug: "deep-sea-survival",
        platform: "steam",
        genres: ["Survival"],
        price: 3.99,
        originalPrice: 15.99,
        discountPercent: 75,
        badges: ["discount"],
      },
      {
        id: "d5",
        title: "Neon Blast",
        slug: "neon-blast",
        platform: "steam",
        genres: ["Shooter"],
        price: 2.15,
        originalPrice: 12.99,
        discountPercent: 83,
        badges: ["discount"],
      },
      {
        id: "d6",
        title: "Cyber Heist",
        slug: "cyber-heist",
        platform: "steam",
        genres: ["Action"],
        price: 4.99,
        originalPrice: 24.99,
        discountPercent: 80,
        badges: ["discount"],
      },
    ],
  },
  {
    label: "Under €10",
    maxPrice: 10,
    games: [
      {
        id: "d7",
        title: "Galactic Trader",
        slug: "galactic-trader",
        platform: "steam",
        genres: ["Simulation"],
        price: 7.99,
        originalPrice: 29.99,
        discountPercent: 73,
        badges: ["discount"],
      },
      {
        id: "d8",
        title: "Frost Kingdom",
        slug: "frost-kingdom",
        platform: "epic",
        genres: ["Strategy"],
        price: 5.49,
        originalPrice: 19.99,
        discountPercent: 73,
        badges: ["discount"],
      },
      {
        id: "d9",
        title: "Turbo Drift",
        slug: "turbo-drift",
        platform: "steam",
        genres: ["Racing"],
        price: 8.99,
        originalPrice: 24.99,
        discountPercent: 64,
        badges: ["discount"],
      },
      {
        id: "d10",
        title: "Rune Warriors",
        slug: "rune-warriors",
        platform: "steam",
        genres: ["RPG"],
        price: 6.49,
        originalPrice: 19.99,
        discountPercent: 68,
        badges: ["discount"],
      },
      {
        id: "d11",
        title: "Colony Craft",
        slug: "colony-craft",
        platform: "steam",
        genres: ["Sandbox"],
        price: 9.99,
        originalPrice: 34.99,
        discountPercent: 71,
        badges: ["discount"],
      },
      {
        id: "d12",
        title: "Dungeon Depths",
        slug: "dungeon-depths",
        platform: "steam",
        genres: ["Roguelike"],
        price: 7.49,
        originalPrice: 22.99,
        discountPercent: 67,
        badges: ["discount"],
      },
    ],
  },
  {
    label: "Under €20",
    maxPrice: 20,
    games: [
      {
        id: "d13",
        title: "Warlords Saga",
        slug: "warlords-saga",
        platform: "steam",
        genres: ["Strategy"],
        price: 14.99,
        originalPrice: 49.99,
        discountPercent: 70,
        badges: ["discount"],
      },
      {
        id: "d14",
        title: "Phantom Coast",
        slug: "phantom-coast",
        platform: "steam",
        genres: ["Adventure"],
        price: 11.99,
        originalPrice: 39.99,
        discountPercent: 70,
        badges: ["discount"],
      },
      {
        id: "d15",
        title: "Apex Zero",
        slug: "apex-zero",
        platform: "playstation",
        genres: ["Shooter"],
        price: 17.99,
        originalPrice: 59.99,
        discountPercent: 70,
        badges: ["discount"],
      },
      {
        id: "d16",
        title: "Terra Nova",
        slug: "terra-nova",
        platform: "steam",
        genres: ["Survival"],
        price: 12.49,
        originalPrice: 44.99,
        discountPercent: 72,
        badges: ["discount"],
      },
      {
        id: "d17",
        title: "Mech Command",
        slug: "mech-command",
        platform: "steam",
        genres: ["Action"],
        price: 15.99,
        originalPrice: 39.99,
        discountPercent: 60,
        badges: ["discount"],
      },
      {
        id: "d18",
        title: "Star Drift",
        slug: "star-drift",
        platform: "epic",
        genres: ["Sci-Fi"],
        price: 18.99,
        originalPrice: 54.99,
        discountPercent: 65,
        badges: ["discount"],
      },
    ],
  },
];

export const genres = [
  "All Genres",
  "Action",
  "RPG",
  "Strategy",
  "Indie",
  "Simulation",
  "Racing",
  "VR Only",
  "Free to Play",
];

export const allPlatforms: { value: Platform; label: string }[] = [
  { value: "steam", label: "Steam" },
  { value: "epic", label: "Epic Games" },
  { value: "xbox", label: "Xbox" },
  { value: "playstation", label: "PlayStation" },
  { value: "switch", label: "Nintendo Switch" },
];

export const allGenres: string[] = [
  "Action",
  "RPG",
  "Strategy",
  "Indie",
  "Simulation",
  "Racing",
  "Sports",
  "Adventure",
  "Shooter",
  "Puzzle",
  "Horror",
  "Platformer",
  "Survival",
  "Sandbox",
  "Fighting",
];

export const catalogGames: Game[] = [
  {
    id: "c1",
    title: "Neural Reckoning: 2099",
    slug: "neural-reckoning-2099",
    platform: "steam",
    genres: ["Action", "RPG"],
    price: 14.99,
    originalPrice: 59.99,
    discountPercent: 75,
    badges: ["discount", "rare"],
  },
  {
    id: "c2",
    title: "Void Walker: Eclipse",
    slug: "void-walker-eclipse",
    platform: "epic",
    genres: ["Adventure", "Action"],
    price: 23.99,
    originalPrice: 39.99,
    discountPercent: 40,
    badges: ["discount"],
  },
  {
    id: "c3",
    title: "Neon Velocity",
    slug: "neon-velocity",
    platform: "steam",
    genres: ["Racing", "Sports"],
    price: 19.99,
    badges: [],
  },
  {
    id: "c4",
    title: "Bit-Shift Chronicles",
    slug: "bit-shift-chronicles",
    platform: "steam",
    genres: ["RPG", "Indie"],
    price: 5.99,
    originalPrice: 29.99,
    discountPercent: 80,
    badges: ["discount"],
  },
  {
    id: "c5",
    title: "Starfield Explorer",
    slug: "starfield-explorer",
    platform: "steam",
    genres: ["RPG", "Adventure"],
    price: 41.99,
    originalPrice: 69.99,
    discountPercent: 40,
    badges: ["discount"],
  },
  {
    id: "c6",
    title: "Phantom Blade Zero",
    slug: "phantom-blade-zero",
    platform: "playstation",
    genres: ["Action", "Fighting"],
    price: 59.99,
    badges: ["new"],
    releaseDate: "2026-03-15",
  },
  {
    id: "c7",
    title: "Frost Kingdom",
    slug: "frost-kingdom",
    platform: "epic",
    genres: ["Strategy", "Survival"],
    price: 5.49,
    originalPrice: 19.99,
    discountPercent: 73,
    badges: ["discount"],
  },
  {
    id: "c8",
    title: "Shadow Runner",
    slug: "shadow-runner",
    platform: "steam",
    genres: ["Platformer", "Indie"],
    price: 1.99,
    originalPrice: 14.99,
    discountPercent: 87,
    badges: ["discount"],
  },
  {
    id: "c9",
    title: "Galactic Trader",
    slug: "galactic-trader",
    platform: "steam",
    genres: ["Simulation", "Strategy"],
    price: 7.99,
    originalPrice: 29.99,
    discountPercent: 73,
    badges: ["discount"],
  },
  {
    id: "c10",
    title: "Warlords Saga",
    slug: "warlords-saga",
    platform: "steam",
    genres: ["Strategy", "RPG"],
    price: 14.99,
    originalPrice: 49.99,
    discountPercent: 70,
    badges: ["discount"],
  },
  {
    id: "c11",
    title: "Apex Zero",
    slug: "apex-zero",
    platform: "playstation",
    genres: ["Shooter", "Action"],
    price: 17.99,
    originalPrice: 59.99,
    discountPercent: 70,
    badges: ["discount"],
  },
  {
    id: "c12",
    title: "Terra Nova",
    slug: "terra-nova",
    platform: "xbox",
    genres: ["Survival", "Adventure"],
    price: 12.49,
    originalPrice: 44.99,
    discountPercent: 72,
    badges: ["discount"],
  },
  {
    id: "c13",
    title: "Mech Command",
    slug: "mech-command",
    platform: "steam",
    genres: ["Action", "Strategy"],
    price: 15.99,
    originalPrice: 39.99,
    discountPercent: 60,
    badges: ["discount"],
  },
  {
    id: "c14",
    title: "Ghost Protocol: Zero",
    slug: "ghost-protocol-zero",
    platform: "steam",
    genres: ["Action", "Shooter"],
    price: 59.99,
    badges: ["new"],
    releaseDate: "2026-03-18",
  },
  {
    id: "c15",
    title: "Neon Pulse",
    slug: "neon-pulse",
    platform: "steam",
    genres: ["Action", "Indie"],
    price: 19.99,
    badges: ["popular"],
  },
  {
    id: "c16",
    title: "Turbo Drift",
    slug: "turbo-drift",
    platform: "switch",
    genres: ["Racing", "Sports"],
    price: 8.99,
    originalPrice: 24.99,
    discountPercent: 64,
    badges: ["discount"],
  },
  {
    id: "c17",
    title: "Rune Warriors",
    slug: "rune-warriors",
    platform: "xbox",
    genres: ["RPG", "Action"],
    price: 6.49,
    originalPrice: 19.99,
    discountPercent: 68,
    badges: ["discount"],
  },
  {
    id: "c18",
    title: "Colony Craft",
    slug: "colony-craft",
    platform: "steam",
    genres: ["Sandbox", "Survival"],
    price: 9.99,
    originalPrice: 34.99,
    discountPercent: 71,
    badges: ["discount"],
  },
  {
    id: "c19",
    title: "Dungeon Depths",
    slug: "dungeon-depths",
    platform: "steam",
    genres: ["RPG", "Indie"],
    price: 7.49,
    originalPrice: 22.99,
    discountPercent: 67,
    badges: ["discount"],
  },
  {
    id: "c20",
    title: "Beyond The Void",
    slug: "beyond-the-void",
    platform: "playstation",
    genres: ["Adventure", "Horror"],
    price: 69.99,
    badges: ["pre-order"],
    timeLeft: "12 Days Left",
  },
  {
    id: "c21",
    title: "Kingdoms of Dust",
    slug: "kingdoms-of-dust",
    platform: "switch",
    genres: ["Strategy", "RPG"],
    price: 44.99,
    badges: ["pre-order"],
    timeLeft: "3 Weeks Left",
  },
  {
    id: "c22",
    title: "Pixel Rogue",
    slug: "pixel-rogue",
    platform: "steam",
    genres: ["Indie", "Platformer"],
    price: 0.89,
    originalPrice: 9.99,
    discountPercent: 91,
    badges: ["discount"],
  },
  {
    id: "c23",
    title: "Lofi Odyssey",
    slug: "lofi-odyssey",
    platform: "steam",
    genres: ["Adventure", "Puzzle"],
    price: 4.5,
    originalPrice: 19.0,
    discountPercent: 76,
    badges: ["discount"],
  },
  {
    id: "c24",
    title: "Deep Sea Survival",
    slug: "deep-sea-survival",
    platform: "epic",
    genres: ["Survival", "Horror"],
    price: 3.99,
    originalPrice: 15.99,
    discountPercent: 75,
    badges: ["discount"],
  },
  {
    id: "c25",
    title: "Star Drift",
    slug: "star-drift",
    platform: "epic",
    genres: ["Simulation", "Indie"],
    price: 18.99,
    originalPrice: 54.99,
    discountPercent: 65,
    badges: ["discount"],
  },
  {
    id: "c26",
    title: "Strike Team Delta",
    slug: "strike-team-delta",
    platform: "xbox",
    genres: ["Shooter", "Action"],
    price: 14.5,
    originalPrice: 19.99,
    discountPercent: 25,
    badges: ["discount", "popular"],
  },
  {
    id: "c27",
    title: "Cyber Heist",
    slug: "cyber-heist",
    platform: "steam",
    genres: ["Action", "Indie"],
    price: 4.99,
    originalPrice: 24.99,
    discountPercent: 80,
    badges: ["discount"],
  },
  {
    id: "c28",
    title: "Phantom Coast",
    slug: "phantom-coast",
    platform: "switch",
    genres: ["Adventure", "Puzzle"],
    price: 11.99,
    originalPrice: 39.99,
    discountPercent: 70,
    badges: ["discount"],
  },
  {
    id: "c29",
    title: "Neon Blast",
    slug: "neon-blast",
    platform: "steam",
    genres: ["Shooter", "Action"],
    price: 2.15,
    originalPrice: 12.99,
    discountPercent: 83,
    badges: ["discount"],
  },
  {
    id: "c30",
    title: "Arcade Legends",
    slug: "arcade-legends",
    platform: "switch",
    genres: ["Indie", "Platformer"],
    price: 12.49,
    badges: ["new"],
    releaseDate: "2026-03-19",
  },
];
